#!/bin/bash
LOCATIONS=(
"/usr/lib/cpupower-gui/cpupower-gui.py"
)

for ((i = 0; i < ${#LOCATIONS[@]}; i++))
do
    if [[ -e "${LOCATIONS[${i}]}" ]]; then
        python3 ${LOCATIONS[${i}]} $1
    fi
done


