name: pre-commit

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install deps
      run: pip3 install black polib pyyaml
    - uses: pre-commit/action@v3.0.0
    - name: Make patch
      if: failure()
      run: git diff > ~/pre-commit.patch
    - name: Upload patch
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: patch
        path: ~/pre-commit.patch
